name: Makefile CI
on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm
      
    - name: Install Dependencies
      run: npm ci
      
    - name: Build Project
      run: make build
    
    - name: Deploy Project
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/
        branch: static

